### ISSUE TITLE
Initial custom post types we should standardize

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/content-type-standards#1]
This is a ticket to list the custom post types that we'd like to standardize for this project.  This ticket is not for addressing naming conventions or anything like that.  It's simply to decide on a list of post types.

This is just an initial list of post types and not in any way all of the post type we'll cover throughout the entire project.  It's just something to get the ball rolling.

**Currently-proposed list:**
- Downloads
- Education / e-Learning (courses, lesson, quizzes)
- Events (see: #4)
- FAQs
- Featured Content / Callouts
- Forms
- Galleries
- Issues / Tickets (issue tracking)
- Listings / Properties
- Locations
- Portfolios / Projects (see: #2)
- Products
- Recipes
- Restaurants (food menus and more)
- Reviews
- Services
- Staff / Team Members / Bios / Person
- Testimonials
- Vehicles
- Films / Movies
- Podcasts / Episodes
- Publications / Books / Etc.
- Slides (for sliders or slideshows)
- Quotes
- Links / Bookmarks

**Edit:** This list is not the actual names of the post types.  It's just a list to get the ball rolling.

**Propose new items:** If you'd like propose new items, leave a comment.

**+1/-1 current items:** If you want to see anything handled (or not) from the above list, just +1/-1 it.

**Comment by kraftner** [comment]
What about Media Response/Press Coverage?

What I am thinking about is a list of news articles/interviews either as pdf scans or a link like to a website with some metadata like date of publication, type and expecially a link to something related like e.g. a portfolio item, a product or maybe some other CPTs.

**Comment by AlchemyUnited** [comment]
moi?

this feel closer to "content object" meta to me. that is, there's some sort of content (you're e.g., PDF) and that has meta data associated with it (e.g., creation date). i think this makes a lot of sense if you get a bit abstract and move from thinking about websites as the traditional page model; and instead think of content as objects (with properties) and those objects are used to build bigger object and eventually pages.

this is especially true if you believe an experience is about building "the right content at the right time for the right visitor."

The current WP model feel mostly page based, at least to me. That said, it also feels like it is evolving, or can evolve with things like the REST API, as well as layout / design engine like Aesop's Lasso. At some point, I would think, this object + meta discussion will need to happen, yes? But is that here? Within JT's scope?

I like this idea, but i'd like to see it applied at a broader more universal level.

too heady? too early? i should probably drink less coffee :)
