### ISSUE TITLE
register_meta usage

### ISSUE THREAD

**Issue by franz-josef-kaiser** [justintadlock/content-type-standards#24]
I know that this has been discussed in #5 already, but I think the assumptions made are kinda off from a UX perspective.

After reviewing the issue with a friend, I see the following two use cases for the function:

 * Turn off visibility in the admin UI in the _Custom Fields_ MetaBox
 * Restrict access to MetaData handling based on capability

The first thing is that using `__return_false` will restrict the Custom Fields visibility for everyone - when you _do not_ use an underscore/`_` prefix. That's ok as you are probably already handling all the things like capability checks, nonces, etc. and building a custom MetaBox with a sophisticated UI yourself. This helps _not_ confusing the user by having two meta boxes where s/he can add/update the same data. But when your plugin gets uninstalled or deactivated this will be reversed and access to altering the data would be possible again via the _Custom Fields_ MetaBox. 

> I suggest to add a note that the `auth_callback` should be set to `__return_false` when there's a MetaBox added. I also suggest to _drop_ the underscore to make it "invisible". This will in all cases leave the user with no access to his own data - unless s/he can handle Adminer or phpMyAdmin or the CLI and  `mysql` command.

When there's _no_ MetaBox added, but you want to restrict access to the field, then the `auth_callback` is nice to have as well. Just [look at the source of `register_meta()`](https://github.com/WordPress/WordPress/blob/f6fd6e09b19d01c6342f0df39ff4fa35983bed8e/wp-includes/meta.php#L1610-L1611) and then at [`~/wp-includes/capabilities.php`](https://github.com/WordPress/WordPress/blob/f6fd6e09b19d01c6342f0df39ff4fa35983bed8e/wp-includes/capabilities.php#L1203-L1221) to see that there's more to it than adding/removing meta data access from a core UI. It's actually offering access to alter the needed capabilities on the fly. This allows very fine grained access to meta data. May it be access for (example) authors with a completed user profile and no access for those who haven't completed it, to stuff depending on post type or another meta key, user votes, some kind of points, etc. This part imo is missing from the documentation.

**Comment by kraftner** [comment]
I've read this twice but I'm still not sure I got this. So what you're advocating for is
- no `_`prefix (to keep data accessible with default UI)
- adding documentation that advises to use `__return_false` when using a MetaBox, and `__return_true` when not using a MetaBox.

If that is correct, what about a PR :wink:

**Comment by justintadlock** [comment]
I'm fine going either way. We just need to decide a route and stick to it.

**Comment by AlchemyUnited** [comment]
re: " the Custom Fields visibility for everyone - when you do not use an underscore/_ prefix. "

fwiw, this feel hack-y (in a bad way). can't there just be a bool for visibility_active? i mean, if for some reason you want to switch that programatically, mucking w/ a lead underscore feel PITA-esque :)

i use an (bool) active flag a lot. it's much easier to switch something on/off then to have to remove it, etc. i wish it was more of general WP best practice.

**Comment by justintadlock** [comment]
I've sat on this a few days and have given this some thought.  I'm thinking we should drop the `_` prefix for the meta key standard.  I can't think of any good reasons for having it to be honest.

So, just +1 this if you agree.  If not, let us know why.  We really need to go ahead and close this because all other custom content standards rely on this.

**Comment by Giuseppe-Mazzapica** [comment]
:+1:

**Comment by kraftner** [comment]
:+1:

**Comment by franz-josef-kaiser** [comment]
:+1:

**Comment by justintadlock** [comment]
I think we have a consensus here. I'm going to leave this ticket open until we can get the Wikis updated.

**Comment by franz-josef-kaiser** [comment]
Here we go: https://github.com/justintadlock/content-type-standards/wiki/Post-Metadata

**Comment by justintadlock** [comment]
All right.  I've updated the code for the two standards we have in place.  And, the other Wiki pages:

* https://github.com/justintadlock/content-type-standards/wiki/Post-Metadata:-Date-Time
* https://github.com/justintadlock/content-type-standards/wiki/Content-Type:-Portfolio
* https://github.com/justintadlock/content-type-standards/wiki/Content-Type:-Testimonial

Anyone feel free to update the Wiki pages if we missed anything.  I'm closing this one.

**Comment by jjeaton** [comment]
The README needs to be updated for this change as well (still recommends `_` prefix for post metadata)

**Comment by kraftner** [comment]
I think the whole README needs a rewrite. Now that stuff is in the wiki it shouldn't be duplicated in the README.

**Comment by justintadlock** [comment]
Yep, I'll get on that soonish.
