### ISSUE TITLE
Set one definitive meta key instead of having exceptions

### ISSUE THREAD

**Issue by franz-josef-kaiser** [justintadlock/content-type-standards#29]
Currently we have the following (See #24 and our [wiki](https://github.com/justintadlock/content-type-standards/wiki/Post-Metadata)):

> ## General naming standards for post metadata keys

> * Meta keys should be all lowercase letters or numbers (`metakey` rather than `Metakey`).
* Meta keys should also be prefixed with the post type name with exceptions for longer post type names (`{$post_type}_thing`).
* If the meta key is intended to be used across multiple post types, ***NO*** `{$post_type}` prefix should be used.
* Multiple words should be split with an underscore (`{$post_type}_thing_a`).

That's pretty much the opposite of a standard. Instead it is a base rule (lower case, letters or numbers/alphanumeric) with a set of _exceptions_. In short: There should be **no exceptions** at all.

Let's discuss a new set of rules _without_ exceptions. The two rules that I recommend taking over from the previous ruleset are:

 + Names should be all lowercase
 + Multiple words should be split with an underscore
 + Names should be alphanumeric only. Matching regex: `"^[a-z0-9_]+$"` (*)

I would add the following additions:

 + There shall be _no_ post type name attached. Meta data should be able to switch from one post type to another (think: renaming a post type) or be able to get attached to additional post types without a problem.
 + Drop conjunctions (`with`), articles (`the`) and other filler words from the meta key name. The use of _conditionals_ is allowed for boolean flags (example: `has_*`, `is_*`) as this is unavoidable to cover different context.

To reiterate the problem with post types: When changing the name of a post type, one would have to alter _all_ meta key names already saved in the DB.

<sup>(*) I know that there could be `\d` used instead, but this is for readability only.</sup>

**Comment by justintadlock** [comment]
+1 to these changes.  It's simpler and more portable across post types.

**Comment by NateWr** [comment]
When implementing this change, are we prefixing post meta with an underscore? So would `_location_phone` now be `_phone` or `phone`?

**Comment by NateWr** [comment]
Sorry guys, my brain forgot we already made the decision to ditch underscores. Ignore my questions.

**Comment by justintadlock** [comment]
Closing this as fixed.
